### ISSUE TITLE
"error return without exception set" then try to set cshigh to False.

### ISSUE THREAD

**Issue by oosavu** [doceme/py-spidev#108]
Raspberry PI Zero W.

Works good on Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 

Fails on Raspberry Pi OS (32-bit) Lite May 2020 (Release date:2020-05-27)

`
import spidev
spi = spidev.SpiDev()
spi.open(0, 1)
spi.cshigh = False
`
![image](https://user-images.githubusercontent.com/8857259/89837762-48103d80-db72-11ea-8373-b70bf676302e.png)

**Comment by JonathonReinhart** [comment]
I think the problem is here: https://github.com/doceme/py-spidev/blob/a5d82b88bd1c95c9f9ec46e9f7afe08c3323e625/spidev_module.c#L904-L906

`__spidev_set_mode` returns `-1` without calling `PyErr_Set*`, which is then returned by `SpiDev_set_cshigh`.

Running this test code:
```python
#!/usr/bin/env python3
import spidev

spi = spidev.SpiDev()
spi.open(0, 0)

spi.cshigh = False
```

I see only these relevant syscalls in `strace`:

```strace
openat(AT_FDCWD, "/dev/spidev0.0", O_RDWR|O_LARGEFILE) = 3
ioctl(3, SPI_IOC_RD_MODE, 0xbea7c23f)   = 0
ioctl(3, SPI_IOC_RD_BITS_PER_WORD, 0xbea7c23f) = 0
ioctl(3, SPI_IOC_RD_MAX_SPEED_HZ, 0xbea7c248) = 0
ioctl(3, SPI_IOC_WR_MODE, 0xbea7d1d7)   = 0
ioctl(3, SPI_IOC_RD_MODE, 0xbea7d1db)   = 0
```

So because none of the `ioctl` calls fail, I have to assume that the attempt to set the `SPI_CS_HIGH` bit was refused by the kernel driver. So `test`, the readback value, didn't match `mode`, the value attempted to be set.

**Comment by jfernandz** [comment]
`cshigh` in fact is `True` by default because if you `print(device.cshigh)` you'll get a True, however I'm having a low-active behavior:

![DS0003](https://user-images.githubusercontent.com/4059108/102777057-22047080-4390-11eb-95a7-dc6025db2597.png)

Why is this?
